name: Windows MinGW 64 build & test

on:
  push:
    branches: ["main"]

jobs:
  build-and-tests:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Install MinGW dependencies
        run: |
            C:/msys64/usr/bin/pacman -S --needed base-devel mingw-w64-ucrt-x86_64-toolchain --noconfirm
            $env:Path += ";C:\msys64\ucrt64\bin"
      - name: Generate
        run: cmake.exe --no-warn-unused-cli -DCMAKE_EXPORT_COMPILE_COMMANDS:BOOL=TRUE -DCMAKE_BUILD_TYPE:STRING=Release -DCMAKE_C_COMPILER:FILEPATH="gcc.exe" -DCMAKE_CXX_COMPILER:FILEPATH="g++.exe" -Btarget -G "MinGW Makefiles"
      - name: Build
        run: cmake --build target -- -j 8
      - name: Test
        run: ctest --test-dir target -j8 -C Release -T test --output-on-failure
      # No test report for the moment
      # - name: Test Report
      #   uses: dorny/test-reporter@v1
      #   if: success() || failure()
      #   with:
      #     name: Windows CityHash Test Report
      #     path: target/test/test_*_report.xml
      #     reporter: java-junit
      - name: Release
        run: |
          mkdir -p release
          cp -R target/test/test_core.exe release -i
          cp -R target/src/*.a release -i
          cp -R interface/core release/core -i
      - name: Upload artifacts
        uses: actions/upload-artifact@v3.1.1
        with:
          name: windows_mingw_64
          path: release\**
